# https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: check-mk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: check-mk
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: cmk-instance
  namespace: check-mk
spec:
  replicas: 1
  baseImage: prom/prometheus
  version: v2.6.0
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      service-monitor: sample-metrics-app # this is for each defined service monitor object
  resources:
    requests:
      memory: 300Mi # Keep track of this value
  retention: 5d
---
apiVersion: v1
kind: Service
metadata:
  name: cmk-instance
  namespace: check-mk
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30999
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: cmk-instance

---
# Inspiration from https://github.com/helm/charts/blob/master/stable/prometheus-operator/templates/exporters/kubelet/servicemonitor.yaml
# still to figure out how to keep this on https internally to the cluster.
# It doesn't matter that for the moment the http port remains always active. At somepoint kubernetes should cancel it.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: system-metrics
  labels:
    service-monitor: sample-metrics-app # This label is matched by the prometheus object
  namespace: check-mk
spec:
  endpoints:
  - port: http-metrics
    interval: 30s
    honorLabels: true
  - port: http-metrics
    path: /metrics/cadvisor
    interval: 30s
    honorLabels: true
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
